version: "3.8"
name: typst

services:
  server:
    container_name: typst-server
    build:
      context: .
      dockerfile_inline: |
        FROM node:22-alpine
        RUN corepack enable && corepack prepare pnpm@latest --activate
        WORKDIR /app
        COPY . .
        RUN pnpm install
        CMD pnpm run start
    environment:
      - HTTPS=false
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - /var/www/typst-templates:/app/files/templates
    networks:
      - traefik
networks:
  traefik:
    external: true
        #    labels:
        #      - "traefik.enable=true"
        #      - "traefik.http.routers.typst-server.rule=Host(`typst.vps.azduha.cz`)"
        #      - "traefik.http.routers.typst-server.tls=true"
        #      - "traefik.http.routers.typst-server.tls.certresolver=lets-encrypt"
        #      - "traefik.http.services.typst-server.loadbalancer.server.port=5000"
